#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr & 
exec picom --experimental-backends &
feh --bg-center ~/Pictures/wallpapers/wallpaper099.jpg

bspc monitor -d "1: Term " "2: Navg " "3: Code " "4: Edit " "5: Spotify " "6: Chat ﭮ"

bspc config border_width         3
bspc config window_gap           8

# Border colors
# bspc config normal_border_color "#ff5733"
bspc config focused_border_color "#00b2ff"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
